branch-defaults:
  master:
    environment: Codeblog-prod
environment-defaults:
  Codeblog-prod:
    branch: master
    repository: codeblog
global:
  application_name: codeblog
  default_ec2_keyname: null
  default_platform: Java 8 running on 64bit Amazon Linux
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
